- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomGear
  equipment:
  # CentComm ivent roles start
    jumpsuit: ClothingUniformJumpsuitCentcomDeputy
    mask: ClothingMaskGasCentcom
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesCentcom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCentcomDeputyCarapace
  # CentComm ivent roles end
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
  # CentComm ivent roles start
    belt: ClothingBeltSheathFilled
    pocket1: ClothingNeckCentcomCloak
    pocket2: BoxFolderCentComClipboard
  # CentComm ivent roles end

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
